### ISSUE TITLE
support for python 3.

### ISSUE THREAD

**Issue by Cologler** [barneygale/isoparser#9]
Or add the python version in pypi.

THANKS. :)

**Comment by minexew** [comment]
FYI I'm going to do this in my fork

**Comment by minexew** [comment]
the fork at https://github.com/dwoz/isoparser claims py3 compatibility

**Comment by Cologler** [comment]
@minexew Good Job! Is possible to release it into pypi?

**Comment by minexew** [comment]
I guess @barneygale would need to merge the 2 tiny commits added in that repo.

**Comment by barneygale** [comment]
I've merged dwoz's fork. Anyone want to test before I put a new version on pypi?

**Comment by Cologler** [comment]
test_iso.py work fine on my PC (python 3.6.0).

**Comment by barneygale** [comment]
Uploaded to pypi!
